### ISSUE TITLE
Its not working for me... Can you please help!!!

### ISSUE THREAD

**Issue by sudhakar-al** [GuerrillaCoder/Upfront-Template-Builder#2]
I followed the steps you have given but its not working for me. 

Can you kindly let me know the issue!!!

Warning: Invalid argument supplied for foreach() in D:\Xampp\htdocs\drag-and-drop\wp-content\plugins\Upfront-Template-Builder-master\upfront-template-builder.php on line 58

Warning: Invalid argument supplied for foreach() in D:\Xampp\htdocs\drag-and-drop\wp-content\plugins\Upfront-Template-Builder-master\upfront-template-builder.php on line 70

Thanks

**Comment by GuerrillaCoder** [comment]
That error means you didn't enter the right page name that saved in database or you didn't select region to export I think.  If I get time I will add some code to make selecting it a bit quicker but for next couple of days I have to finish off this template.

Here is video showing how I use it.  MAclub is my storage key, if your using spirit it is "Spirit".  Not sure what the other ones are.  I'll make that bit better in the next update.

https://dl.dropboxusercontent.com/u/19226543/usingplugin.mp4

**Comment by sudhakar-al** [comment]
Thank you so much for your reply. 

I want to know one more thing. Until one page is updated, these options are not saving in the db right.

Because of that may be i got that issue.

Thanks for the best solution for creating this plugin.

Thanks,
Sudhakar

**Comment by GuerrillaCoder** [comment]
The way the plugin works is it loads a saved layout and creates the PHP for the layout file.  So you have to make and save a page in the upfront editor first then enter the slug in the plugin and select the region you want to generate code for.

It seems to work fine, you just have to remember to update things like links to images manually.

Let me know if it work for you.

**Comment by sudhakar-al** [comment]
Thank you once again for your response!

Really appreciate that!!!

Its working fine for me thanks...

**Comment by GuerrillaCoder** [comment]
Great! Glad I could help.

They do have come code that replaces {{upfront:tag_name}} with a value that can be used for URL's.  When I have some time I might look into trying to incorporate it but I am reluctant to spend too much time on this as they have said their template builder will be released before the end of the year so could come out any day.
