### ISSUE TITLE
Custom post types?

### ISSUE THREAD

**Issue by kosir** [GuerrillaCoder/Upfront-Template-Builder#4]
Hi, I like upfront theme, but it is completely unusable for my custom post types. Can your Template builder make templates also for custom post types?

**Comment by GuerrillaCoder** [comment]
Hi Kosir,

I guess it depends on the use case.  Some plugins override the way upfront works so only the custom content is displayed and not the actual upfront template.  In that case then you would have to alter the plugin code.  

Can you give me an example?

I haven't worked with upfront for a few months as there are so many bugs in it and it is such a pain having to re-apply all my fixes that the dev team don't integrate after every update so it's not that fresh in my mind but if you can show me the situation maybe I can help.

**Comment by kosir** [comment]
Thanks, It was upfront bug, I found solution on their forum. Thanks.
